### ISSUE TITLE
Accessibility - Sectors Screen - TalkBack Not Reading Table Heading Order Properly

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#10]
When using TalkBack to read the sectors screen table headings reading order, it's reading the one that spans three columns first and then the one on the left by itself followed by the other three. I would expect the table heading to be read from left to right then top to bottom. Meaning the first column followed by the one that spans three columns and the three columns below that one,

Please see screenshot example that shows the current reading order using numbers and the expected order using letters. Not number/lettering expect the few pieces of information near the part being skipped. To make it easier I have highlighted with a red border the items that go together.

![bls - android - sectors screen showing current reading order with talkback and expected reading order](https://user-images.githubusercontent.com/10423487/56763365-371a9d80-6770-11e9-8237-6fec350f9fb8.png)

**Comment by greg-gruse** [comment]
I have a fix for this and it will be in the next build

**Comment by jfc3-dol** [comment]
I look forward to testing when you are ready with the next build.

**Comment by jfc3-dol** [comment]
@greg-gruse 

After looking at this again, I am wondering if the text "Employment Level (in thousands)" only supposed to be over the last two columns and not the three? If so I would expect TalkBack to read "Industry Code", "Level", "Employment Level (in thousands)", "1 Month Change" and then "12 Month Change". 

If so please make that correction.

**Comment by greg-gruse** [comment]
No its for all 3 columns.

**Comment by jfc3-dol** [comment]
Okay, wasn't sure when I looked it again showing our QA tester. Wanted to show her in case she would get asked to look at the application if I was out or something.

**Comment by greg-gruse** [comment]
This should be fixed in the  May 8th build?

**Comment by jfc3-dol** [comment]
TalkBack is reading the TABLE headings in the order I expected so I'm going to close this issue.

But we noticed on the city/metro detail screen that the words "(in thousands) were missing and that there were two sets of sorts above each TABLE column on the right. Will be opening two new issues for these problems.
