### ISSUE TITLE
Functional - Metro - On Detail Screens Back Button Takes User Back to Main Search Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#12]
When I'm on a detailed screen past the main metro/city screen, the back button takes the user back to main search screen while the iOS version takes them back one screen to the previous one they were on. Not sure if that is the way Android works or it was designed or not. The only reason I noticed the difference is because I have tested both applications and it would be noticed by others unless they switch phones.

**Comment by greg-gruse** [comment]
It should just take the user back on screen. I find that on my device if I'm not careful the HOME button in the top left stays active and if I press the back button twice it doesn't take it as a back press but rather a HOME press. If I'm careful and make sure the back button is highlighted then double tap it I will just go back one screen.

Can you try it again?

**Comment by jfc3-dol** [comment]
Either if I'm using TalkBack or not the home button (house icon) takes me back to the main home screen when I'm a few levels deep in the  city information or state or county.

I'm using a Samsung Galaxy S7 (model SM-G930V ) running Android 7.0, which is our newest device.

**Comment by greg-gruse** [comment]
Can you please retest this on the May 8th build?

**Comment by jfc3-dol** [comment]
When I double tap on the house icon (back button), it takes me back to the main screen, but if I use the physical back button on my phone, it takes me back one screen at a time.

**Comment by greg-gruse** [comment]
This is the desired behavior, home goes back to the home screen the back button goes back only one screen.

**Comment by jfc3-dol** [comment]
Thanks, for clarifying for someone who doesn't use Android except when testing applications.

I will close this issue.
