### ISSUE TITLE
Functional - County- On Detail Screens Back Button Takes User Back to Main Search Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#14]
When I'm on a detailed screen past the main county screen, the back button takes the user back to main search screen while the iOS version takes them back one screen to the previous one they were on. Not sure if that is the way Android works or it was designed or not. The only reason I noticed the difference is because I have tested both applications and it would be noticed by others unless they switch phones.

**Comment by greg-gruse** [comment]
It should just take the user back on screen.   I find that on my device if I'm not careful the HOME button in the top left stays active and if I press the back button twice it doesn't take it as a back press but rather a HOME press.   If I'm careful and make sure the back button is highlighted then double tap it I will just go back one screen.   

Can you try it again?

**Comment by jfc3-dol** [comment]
Either if I'm using TalkBack or not the home button (house icon) takes me back to the main home screen when I'm a few levels deep in the city information or state or county.

I'm using a Samsung Galaxy S7 (model SM-G930V ) running Android 7.0, which is our newest device.

**Comment by greg-gruse** [comment]
Android has a built in back button at the bottom of the device, on older phones this was a physical button, on newer phones it's a soft button.  You should see 3 of them at the bottom on the screen the triangle is the back (or sometimes down when the keyboard is showing), the circle is like the iPhone home button and the square on the right brings up the task switcher.

It's then considered best practices to NOT have an app specific back button in the top left corner of the screen.  Subsequently the Android version only has a Home button which takes you back to the home screen.

**Comment by jfc3-dol** [comment]
As stated earlier I was expecting the same functionality as the iOS version that the Home icon took me back one screen instead of all the way back to the home screen especially since I'm not an Android person.

If that is how most Android users will expect it to work, we can close these three issues.

**Comment by greg-gruse** [comment]
Yes, that is how they expect it to work.  You should find another "HOME" button the house looking thing on the iOS version that takes you all the way back as well.  

Should I close this or you?

**Comment by jfc3-dol** [comment]
I can close them. 

We tend to let the person that opened the issue close them, so they know it's completed instead of someone else.

Could you please put the text from your comment above explaining how Android users use hardware button to go back one screen and home icon to go back to the main screen in the other two issues and then I will close them, so people know why it was closed?

**Comment by jfc3-dol** [comment]
Closing this issue because I didn't realize Android users use the physical back button to go back one screen and the home icon to take them back to the main/starting screen.
