### ISSUE TITLE
Functional - Display Issue with City Industry Sectors Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#16]
While testing the application with TalkBack, I noticed the following display issue with text covering up part of the drop-down.

Please see attached screenshot.

![bls - android - display issue with indsutry sectors screen from city](https://user-images.githubusercontent.com/10423487/56975539-0905d680-6b3f-11e9-8eb7-b220b5cb6af1.png)

**Comment by greg-gruse** [comment]
I will address in the next build.

**Comment by jfc3-dol** [comment]
Thanks, for making the names break over more than one line instead of making on one line, so we are less liking to have text overlap the drop-down list.

I will close this issue.
