### ISSUE TITLE
Functional - Metro Screen - TABLE Heading Text Missing Content

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#18]
While testing, we noticed that the text "Employment Level" didn't have the words "in thousands" below it as it does on other screens.

Please see attached screenshot.

![bls - android - detail city screen - missing in thousands text](https://user-images.githubusercontent.com/10423487/57399448-3c7bdd00-719f-11e9-9074-ea1c4c3ec09e.png)

**Comment by greg-gruse** [comment]
These values are not in thousands.

**Comment by jfc3-dol** [comment]
Thanks, for clarifying.

I'm going to close this issue.
