### ISSUE TITLE
Functional - County Detail Screen - Why No Numbers under Text on Table Rows

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#20]
While we, were testing we noticed that on the county detail screen the eight digit numbers are missing under the text in the "Industry Code" column or whatever is in the first column.

Please see the attached screenshot.

![bls - android - detail city screen - why does this screen not have the eight digit numbers under them like the metro and state detail screens do](https://user-images.githubusercontent.com/10423487/57401272-48699e00-71a3-11e9-900b-832c1b286893.png)

**Comment by greg-gruse** [comment]
Our client did not want the codes to displayed for this county data.  Suggest closing this issue.

**Comment by jfc3-dol** [comment]
Thanks, for clarifying that this screen does not have the number under the text in the first column like the other screens.

I'm going to close this issue.
