### ISSUE TITLE
Accessibility - Metro, State, and County Detail Screens - TalkBack Not Telling User Column Sorted

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#21]
For the Metro, State, and County Detail screens TalkBack is not telling the user which column got sorted, but at least it's saying the direction. I would expect TalkBack to announce "Sorted Ascending 12-month change" or 12-month change sorted ascending" or whatever order or column it is.

**Comment by greg-gruse** [comment]
The client only wanted these columns sortable.  Suggest closing this issue.

**Comment by greg-gruse** [comment]
I think this is the same behavior as iOS, when the user taps the first time on the sort button it says "Sort by 12 month change, double tap to activate"  then when they double tap it is says "sorted ascending".  It seems to me the first message provides the information needed.

**Comment by jfc3-dol** [comment]
Thanks, for clarifying that Android doesn't tell user which item was sorted.

I'm going to close this issue.
