### ISSUE TITLE
Accssibility - About - Need to Add Headings to "About" Page

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#4]
Need to make "About" text a heading along with description being read separately in TalkBack from the home screen of the "About" page.

Also, need to make the text "Glossary" and the "glossary terms" a heading from the other non home page screens.

**Comment by greg-gruse** [comment]
I've made the About heading on the about screen, the glossary heading and about heading on the other screens as well.

This will be in the next build.

**Comment by greg-gruse** [comment]
This should be fixed in the May 8th build?

**Comment by jfc3-dol** [comment]
Thanks, for making the words "About" and "Glossary" headings but making the glossary term that is bold also a heading would allow users to skip over terms.

**Comment by greg-gruse** [comment]
This should be fixed in the next build.

**Comment by jfc3-dol** [comment]
Thanks, for making the bold glossary term text a heading so a user will know when they get to a new term.

I am closing this issue.
