### ISSUE TITLE
Accessibility - Country - The Word "County" Needs to be a Heading

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#5]
On the county screen the word "County" is not set as a heading like it was done on the "Metro Area" screen. Please make "County" a heading so TalkBack users know what screen they are on.

**Comment by greg-gruse** [comment]
This will be fixed in the next build.

**Comment by greg-gruse** [comment]
This should be fixed in the May 8th build?

**Comment by jfc3-dol** [comment]
Thanks, for making the "County" name now a heading but why is the text in the gray boxes not a heading anymore? Thought that text such as "Unemployment", "Employment and Wages", etc. were headings before and are not now? TalkBack is reading it as a list item for some reason.

**Comment by greg-gruse** [comment]
This will be fixed in the next build.

**Comment by jfc3-dol** [comment]
The text in the gray boxes which are supposed to be headings are not being read as a heading. Some even read them as  text with a list of "X" number of items.

**Comment by jfc3-dol** [comment]
TalkBack is now reading the other gray boxes as headings. For the "Private" heading TalkBack reads as a heading and then "list XYZ items" where XYZ is a number. Not sure why one heading would be part of a set of list items and the rest are not.

When was the minus sign added to the left of the headings in the gray box?

**Comment by jfc3-dol** [comment]
Thanks, for removing the minus sign from in front of the headings.

 For the "Private" and other headings, TalkBack reads as a heading and then "list XYZ items" where XYZ is a number. Not sure why TalkBack is thinking the heading is part of a list or that there is a list under it because it's not reading the items under as list items.

**Comment by jfc3-dol** [comment]
TalkBack is not reading the more details button with only the text from the first column and not the numbers.

For some reason now when I'm on the button and double tap as instructed to see more details it doesn't go to another screen but if I move TalkBack to any other items on the row and double tap it goes the more details. The issue applies to all three detail pages (metro, state, and county). Going close this issues it's has been corrected and open a new one for the new problem above.
