### ISSUE TITLE
Accessibility - Metro - The Word "City Name" Needs to be a Heading

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#7]
On the county screen the "City Name" is not set as a heading. Please make the "City Name" a heading so TalkBack users know what screen they are on.

**Comment by greg-gruse** [comment]
This will be fixed in the next build.

**Comment by greg-gruse** [comment]
This should be fixed in the May 8th build?

**Comment by jfc3-dol** [comment]
Thanks, for making the "City Name" now a heading but why is the text in the gray boxes not a heading anymore? Thought that text such as "Unemployment Rate", "Industry Employment", etc. were headings before and are not now? TalkBack is reading it as a list item for some reason.

**Comment by greg-gruse** [comment]
Sorry to say this again but the gray boxes are reading as headings on my device (which is a Pixel 2 - Android version 9), let me know your os and device and I will investigate.

**Comment by jfc3-dol** [comment]
We are using two devices for are testing and they are the following:

- Samsung Galaxy 7S running Android 7.0
- Samsung Galaxy Tab S running Android 6.0.1

**Comment by greg-gruse** [comment]
Fixed in the next build

**Comment by jfc3-dol** [comment]
The text in the gray boxes which are supposed to be headings are not being read as a heading. Some even read them as text with a list of "X" number of items.

**Comment by jfc3-dol** [comment]
TalkBack is reading the text in the gray boxes as a heading now.

So I'm going to close the issue.
