### ISSUE TITLE
Accessibility - Quesiton - Main Screen - Headings

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#8]
Why when using TalkBack on the main screen with the "State" option chosen does it read "state heading double tap to activate" but does nothing if you tap on it? Same applies for the text "Metro Area" or "county" when those items are selected in the options above.

**Comment by greg-gruse** [comment]
This is an Android behavior that is odd...  I tried several things to override but cannot change that phrase "double tap to activate" when I agree it really shouldn't be there.

I did a quick check of other android apps and found the same behavior in their Google Play Store app, the top tab bar has "Home" select but if you tap on it says "double tap to activate" when it's already active.

**Comment by greg-gruse** [comment]
Suggest close as an Android behavior: 

I did a quick check of other android apps and found the same behavior in their Google Play Store app, the top tab bar has "Home" select but if you tap on it says "double tap to activate" when it's already active.

**Comment by jfc3-dol** [comment]
Okay, at least it wasn't crashing the application like when I was on the iOS version or was it another projects Android version.

If that's the way this works, then we can close the issue.
