### ISSUE TITLE
Accessibility - TalkBack Not Reading Heading and More Details Buttons

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#9]
When using TalkBack to read the contents of an individual city/metro or county or state, it skips over the new heading and the associated button. By skipping the heading and button text, the user does not know what section the information is being used to denote. To get to the sectors/more details screen I had to manually tap on the right facing arrow/button to see them.

Please see screenshot example that shows the current reading order using numbers and the expected order using letters. Not number/lettering expect the few pieces of information near the part being skipped. To make it easier I have highlighted with a red border the items that go together.

![bls - android - county screen showing current reading order with talkback and expected reading order](https://user-images.githubusercontent.com/10423487/56762575-2b2ddc00-676e-11e9-8fc7-a0aee486f7ce.png)

**Comment by greg-gruse** [comment]
I've fixed this and it will be available in the next build.

**Comment by jfc3-dol** [comment]
Thanks, for making the fix and looking forward to reviewing the changes.

I am assuming you made the change to all the similar screens and not only the one I mentioned.

**Comment by greg-gruse** [comment]
Yes this will be fixed on all of the screens

**Comment by greg-gruse** [comment]
This should be fixed in the  May 8th build?

**Comment by jfc3-dol** [comment]
Checked the headings with the more detail button on the metro, state, and county screens and they all worked now as expected. 

So I'm closing the issue.
